pokedex = {
    1: {"name": "Bulbasaur", "type": ["Grass", "Poison"]},
    2: {"name": "Ivysaur", "type": ["Grass", "Poison"]},
    3: {"name": "Venusaur", "type": ["Grass", "Poison"]},
    4: {"name": "Charmander", "type": ["Fire"]},
    5: {"name": "Charmeleon", "type": ["Fire"]},
    6: {"name": "Charizard", "type": ["Fire", "Flying"]},
    7: {"name": "Squirtle", "type": ["Water"]},
    8: {"name": "Wartortle", "type": ["Water"]},
    9: {"name": "Blastoise", "type": ["Water"]},
    10: {"name": "Caterpie", "type": ["Bug"]},
    11: {"name": "Metapod", "type": ["Bug"]},
    12: {"name": "Butterfree", "type": ["Bug", "Flying"]},
    13: {"name": "Weedle", "type": ["Bug", "Poison"]},
    14: {"name": "Kakuna", "type": ["Bug", "Poison"]},
    15: {"name": "Beedrill", "type": ["Bug", "Poison"]},
    16: {"name": "Pidgey", "type": ["Normal", "Flying"]},
    17: {"name": "Pidgeotto", "type": ["Normal", "Flying"]},
    18: {"name": "Pidgeot", "type": ["Normal", "Flying"]},
    19: {"name": "Rattata", "type": ["Normal"]},
    20: {"name": "Raticate", "type": ["Normal"]},
    21: {"name": "Spearow", "type": ["Normal", "Flying"]},
    22: {"name": "Fearow", "type": ["Normal", "Flying"]},
    23: {"name": "Ekans", "type": ["Poison"]},
    24: {"name": "Arbok", "type": ["Poison"]},
    25: {"name": "Pikachu", "type": ["Electric"]},
    26: {"name": "Raichu", "type": ["Electric"]},
    27: {"name": "Sandshrew", "type": ["Ground"]},
    28: {"name": "Sandslash", "type": ["Ground"]},
    29: {"name": "Nidoran", "type": ["Poison"]},
    30: {"name": "Nidorina", "type": ["Poison"]},
    31: {"name": "Nidoqueen", "type": ["Poison", "Ground"]},
    32: {"name": "Nidoran", "type": ["Poison"]},
    33: {"name": "Nidorino", "type": ["Poison"]},
    34: {"name": "Nidoking", "type": ["Poison", "Ground"]},
    35: {"name": "Clefairy", "type": ["Fairy"]},
    36: {"name": "Clefable", "type": ["Fairy"]},
    37: {"name": "Vulpix", "type": ["Fire"]},
    38: {"name": "Ninetales", "type": ["Fire"]},
    39: {"name": "Jigglypuff", "type": ["Normal", "Fairy"]},
    40: {"name": "Wigglytuff", "type": ["Normal", "Fairy"]},
    41: {"name": "Zubat", "type": ["Poison", "Flying"]},
    42: {"name": "Golbat", "type": ["Poison", "Flying"]},
    43: {"name": "Oddish", "type": ["Grass", "Poison"]},
    44: {"name": "Gloom", "type": ["Grass", "Poison"]},
    45: {"name": "Vileplume", "type": ["Grass", "Poison"]},
    46: {"name": "Paras", "type": ["Bug", "Grass"]},
    47: {"name": "Parasect", "type": ["Bug", "Grass"]},
    48: {"name": "Venonat", "type": ["Bug", "Poison"]},
    49: {"name": "Venomoth", "type": ["Bug", "Poison"]},
    50: {"name": "Diglett", "type": ["Ground"]},
    51: {"name": "Dugtrio", "type": ["Ground"]},
    52: {"name": "Meowth", "type": ["Normal"]},
    53: {"name": "Persian", "type": ["Normal"]},
    54: {"name": "Psyduck", "type": ["Water"]},
    55: {"name": "Golduck", "type": ["Water"]},
    56: {"name": "Mankey", "type": ["Fighting"]},
    57: {"name": "Primeape", "type": ["Fighting"]},
    58: {"name": "Growlithe", "type": ["Fire"]},
    59: {"name": "Arcanine", "type": ["Fire"]},
    60: {"name": "Poliwag", "type": ["Water"]},
    61: {"name": "Poliwhirl", "type": ["Water"]},
    62: {"name": "Poliwrath", "type": ["Water", "Fighting"]},
    63: {"name": "Abra", "type": ["Psychic"]},
    64: {"name": "Kadabra", "type": ["Psychic"]},
    65: {"name": "Alakazam", "type": ["Psychic"]},
    66: {"name": "Machop", "type": ["Fighting"]},
    67: {"name": "Machoke", "type": ["Fighting"]},
    68: {"name": "Machamp", "type": ["Fighting"]},
    69: {"name": "Bellsprout", "type": ["Grass", "Poison"]},
    70: {"name": "Weepinbell", "type": ["Grass", "Poison"]},
    71: {"name": "Victreebel", "type": ["Grass", "Poison"]},
    72: {"name": "Tentacool", "type": ["Water", "Poison"]},
    73: {"name": "Tentacruel", "type": ["Water", "Poison"]},
    74: {"name": "Geodude", "type": ["Rock", "Ground"]},
    75: {"name": "Graveler", "type": ["Rock", "Ground"]},
    76: {"name": "Golem", "type": ["Rock", "Ground"]},
    77: {"name": "Ponyta", "type": ["Fire"]},
    78: {"name": "Rapidash", "type": ["Fire"]},
    79: {"name": "Slowpoke", "type": ["Water", "Psychic"]},
    80: {"name": "Slowbro", "type": ["Water", "Psychic"]},
    81: {"name": "Magnemite", "type": ["Electric", "Steel"]},
    82: {"name": "Magneton", "type": ["Electric", "Steel"]},
    83: {"name": "Farfetch'd", "type": ["Normal", "Flying"]},
    84: {"name": "Doduo", "type": ["Normal", "Flying"]},
    85: {"name": "Dodrio", "type": ["Normal", "Flying"]},
    86: {"name": "Seel", "type": ["Water"]},
    87: {"name": "Dewgong", "type": ["Water", "Ice"]},
    88: {"name": "Grimer", "type": ["Poison"]},
    89: {"name": "Muk", "type": ["Poison"]},
    90: {"name": "Shellder", "type": ["Water"]},
    91: {"name": "Cloyster", "type": ["Water", "Ice"]},
    92: {"name": "Gastly", "type": ["Ghost", "Poison"]},
    93: {"name": "Haunter", "type": ["Ghost", "Poison"]},
    94: {"name": "Gengar", "type": ["Ghost", "Poison"]},
    95: {"name": "Onix", "type": ["Rock", "Ground"]},
    96: {"name": "Drowzee", "type": ["Psychic"]},
    97: {"name": "Hypno", "type": ["Psychic"]},
    98: {"name": "Krabby", "type": ["Water"]},
    99: {"name": "Kingler", "type": ["Water"]},
    100: {"name": "Voltorb", "type": ["Electric"]},
    101: {"name": "Electrode", "type": ["Electric"]},
    102: {"name": "Exeggcute", "type": ["Grass", "Psychic"]},
    103: {"name": "Exeggutor", "type": ["Grass", "Psychic"]},
    104: {"name": "Cubone", "type": ["Ground"]},
    105: {"name": "Marowak", "type": ["Ground"]},
    106: {"name": "Hitmonlee", "type": ["Fighting"]},
    107: {"name": "Hitmonchan", "type": ["Fighting"]},
    108: {"name": "Lickitung", "type": ["Normal"]},
    109: {"name": "Koffing", "type": ["Poison"]},
    110: {"name": "Weezing", "type": ["Poison"]},
    111: {"name": "Rhyhorn", "type": ["Ground", "Rock"]},
    112: {"name": "Rhydon", "type": ["Ground", "Rock"]},
    113: {"name": "Chansey", "type": ["Normal"]},
    114: {"name": "Tangela", "type": ["Grass"]},
    115: {"name": "Kangaskhan", "type": ["Normal"]},
    116: {"name": "Horsea", "type": ["Water"]},
    117: {"name": "Seadra", "type": ["Water"]},
    118: {"name": "Goldeen", "type": ["Water"]},
    119: {"name": "Seaking", "type": ["Water"]},
    120: {"name": "Staryu", "type": ["Water"]},
    121: {"name": "Starmie", "type": ["Water", "Psychic"]},
    122: {"name": "Mr. Mime", "type": ["Psychic", "Fairy"]},
    123: {"name": "Scyther", "type": ["Bug", "Flying"]},
    124: {"name": "Jynx", "type": ["Ice", "Psychic"]},
    125: {"name": "Electabuzz", "type": ["Electric"]},
    126: {"name": "Magmar", "type": ["Fire"]},
    127: {"name": "Pinsir", "type": ["Bug"]},
    128: {"name": "Tauros", "type": ["Normal"]},
    129: {"name": "Magikarp", "type": ["Water"]},
    130: {"name": "Gyarados", "type": ["Water", "Flying"]},
    131: {"name": "Lapras", "type": ["Water", "Ice"]},
    132: {"name": "Ditto", "type": ["Normal"]},
    133: {"name": "Eevee", "type": ["Normal"]},
    134: {"name": "Vaporeon", "type": ["Water"]},
    135: {"name": "Jolteon", "type": ["Electric"]},
    136: {"name": "Flareon", "type": ["Fire"]},
    137: {"name": "Porygon", "type": ["Normal"]},
    138: {"name": "Omanyte", "type": ["Rock", "Water"]},
    139: {"name": "Omastar", "type": ["Rock", "Water"]},
    140: {"name": "Kabuto", "type": ["Rock", "Water"]},
    141: {"name": "Kabutops", "type": ["Rock", "Water"]},
    142: {"name": "Aerodactyl", "type": ["Rock", "Flying"]},
    143: {"name": "Snorlax", "type": ["Normal"]},
    144: {"name": "Articuno", "type": ["Ice", "Flying"]},
    145: {"name": "Zapdos", "type": ["Electric", "Flying"]},
    146: {"name": "Moltres", "type": ["Fire", "Flying"]},
    147: {"name": "Dratini", "type": ["Dragon"]},
    148: {"name": "Dragonair", "type": ["Dragon"]},
    149: {"name": "Dragonite", "type": ["Dragon", "Flying"]},
    150: {"name": "Mewtwo", "type": ["Psychic"]},
    151: {"name": "Mew", "type": ["Psychic"]},
    152: {"name": "Chikorita", "type": ["Grass"]},
    153: {"name": "Bayleef", "type": ["Grass"]},
    154: {"name": "Meganium", "type": ["Grass"]},
    155: {"name": "Cyndaquil", "type": ["Fire"]},
    156: {"name": "Quilava", "type": ["Fire"]},
    157: {"name": "Typhlosion", "type": ["Fire"]},
    158: {"name": "Totodile", "type": ["Water"]},
    159: {"name": "Croconaw", "type": ["Water"]},
    160: {"name": "Feraligatr", "type": ["Water"]},
    161: {"name": "Sentret", "type": ["Normal"]},
    162: {"name": "Furret", "type": ["Normal"]},
    163: {"name": "Hoothoot", "type": ["Normal", "Flying"]},
    164: {"name": "Noctowl", "type": ["Normal", "Flying"]},
    165: {"name": "Ledyba", "type": ["Bug", "Flying"]},
    166: {"name": "Ledian", "type": ["Bug", "Flying"]},
    167: {"name": "Spinarak", "type": ["Bug", "Poison"]},
    168: {"name": "Ariados", "type": ["Bug", "Poison"]},
    169: {"name": "Crobat", "type": ["Poison", "Flying"]},
    170: {"name": "Chinchou", "type": ["Water", "Electric"]},
    171: {"name": "Lanturn", "type": ["Water", "Electric"]},
    172: {"name": "Pichu", "type": ["Electric"]},
    173: {"name": "Cleffa", "type": ["Fairy"]},
    174: {"name": "Igglybuff", "type": ["Normal", "Fairy"]},
    175: {"name": "Togepi", "type": ["Fairy"]},
    176: {"name": "Togetic", "type": ["Fairy", "Flying"]},
    177: {"name": "Natu", "type": ["Psychic", "Flying"]},
    178: {"name": "Xatu", "type": ["Psychic", "Flying"]},
    179: {"name": "Mareep", "type": ["Electric"]},
    180: {"name": "Flaaffy", "type": ["Electric"]},
    181: {"name": "Ampharos", "type": ["Electric"]},
    182: {"name": "Bellossom", "type": ["Grass"]},
    183: {"name": "Marill", "type": ["Water", "Fairy"]},
    184: {"name": "Azumarill", "type": ["Water", "Fairy"]},
    185: {"name": "Sudowoodo", "type": ["Rock"]},
    186: {"name": "Politoed", "type": ["Water"]},
    187: {"name": "Hoppip", "type": ["Grass", "Flying"]},
    188: {"name": "Skiploom", "type": ["Grass", "Flying"]},
    189: {"name": "Jumpluff", "type": ["Grass", "Flying"]},
    190: {"name": "Aipom", "type": ["Normal"]},
    191: {"name": "Sunkern", "type": ["Grass"]},
    192: {"name": "Sunflora", "type": ["Grass"]},
    193: {"name": "Yanma", "type": ["Bug", "Flying"]},
    194: {"name": "Wooper", "type": ["Water", "Ground"]},
    195: {"name": "Quagsire", "type": ["Water", "Ground"]},
    196: {"name": "Espeon", "type": ["Psychic"]},
    197: {"name": "Umbreon", "type": ["Dark"]},
    198: {"name": "Murkrow", "type": ["Dark", "Flying"]},
    199: {"name": "Slowking", "type": ["Water", "Psychic"]},
    200: {"name": "Misdreavus", "type": ["Ghost"]},
    201: {"name": "Unown", "type": ["Psychic"]},
    202: {"name": "Wobbuffet", "type": ["Psychic"]},
    203: {"name": "Girafarig", "type": ["Normal", "Psychic"]},
    204: {"name": "Pineco", "type": ["Bug"]},
    205: {"name": "Forretress", "type": ["Bug", "Steel"]},
    206: {"name": "Dunsparce", "type": ["Normal"]},
    207: {"name": "Gligar", "type": ["Ground", "Flying"]},
    208: {"name": "Steelix", "type": ["Steel", "Ground"]},
    209: {"name": "Snubbull", "type": ["Fairy"]},
    210: {"name": "Granbull", "type": ["Fairy"]},
    211: {"name": "Qwilfish", "type": ["Water", "Poison"]},
    212: {"name": "Scizor", "type": ["Bug", "Steel"]},
    213: {"name": "Shuckle", "type": ["Bug", "Rock"]},
    214: {"name": "Heracross", "type": ["Bug", "Fighting"]},
    215: {"name": "Sneasel", "type": ["Dark", "Ice"]},
    216: {"name": "Teddiursa", "type": ["Normal"]},
    217: {"name": "Ursaring", "type": ["Normal"]},
    218: {"name": "Slugma", "type": ["Fire"]},
    219: {"name": "Magcargo", "type": ["Fire", "Rock"]},
    220: {"name": "Swinub", "type": ["Ice", "Ground"]},
    221: {"name": "Piloswine", "type": ["Ice", "Ground"]},
    222: {"name": "Corsola", "type": ["Water", "Rock"]},
    223: {"name": "Remoraid", "type": ["Water"]},
    224: {"name": "Octillery", "type": ["Water"]},
    225: {"name": "Delibird", "type": ["Ice", "Flying"]},
    226: {"name": "Mantine", "type": ["Water", "Flying"]},
    227: {"name": "Skarmory", "type": ["Steel", "Flying"]},
    228: {"name": "Houndour", "type": ["Dark", "Fire"]},
    229: {"name": "Houndoom", "type": ["Dark", "Fire"]},
    230: {"name": "Kingdra", "type": ["Water", "Dragon"]},
    231: {"name": "Phanpy", "type": ["Ground"]},
    232: {"name": "Donphan", "type": ["Ground"]},
    233: {"name": "Porygon2", "type": ["Normal"]},
    234: {"name": "Stantler", "type": ["Normal"]},
    235: {"name": "Smeargle", "type": ["Normal"]},
    236: {"name": "Tyrogue", "type": ["Fighting"]},
    237: {"name": "Hitmontop", "type": ["Fighting"]},
    238: {"name": "Smoochum", "type": ["Ice", "Psychic"]},
    239: {"name": "Elekid", "type": ["Electric"]},
    240: {"name": "Magby", "type": ["Fire"]},
    241: {"name": "Miltank", "type": ["Normal"]},
    242: {"name": "Blissey", "type": ["Normal"]},
    243: {"name": "Raikou", "type": ["Electric"]},
    244: {"name": "Entei", "type": ["Fire"]},
    245: {"name": "Suicune", "type": ["Water"]},
    246: {"name": "Larvitar", "type": ["Rock", "Ground"]},
    247: {"name": "Pupitar", "type": ["Rock", "Ground"]},
    248: {"name": "Tyranitar", "type": ["Rock", "Dark"]},
    249: {"name": "Lugia", "type": ["Psychic", "Flying"]},
    250: {"name": "Ho-Oh", "type": ["Fire", "Flying"]},
    251: {"name": "Celebi", "type": ["Psychic", "Grass"]},
    252: {"name": "Treecko", "type": ["Grass"]},
    253: {"name": "Grovyle", "type": ["Grass"]},
    254: {"name": "Sceptile", "type": ["Grass"]},
    255: {"name": "Torchic", "type": ["Fire"]},
    256: {"name": "Combusken", "type": ["Fire", "Fighting"]},
    257: {"name": "Blaziken", "type": ["Fire", "Fighting"]},
    258: {"name": "Mudkip", "type": ["Water"]},
    259: {"name": "Marshtomp", "type": ["Water", "Ground"]},
    260: {"name": "Swampert", "type": ["Water", "Ground"]},
    261: {"name": "Poochyena", "type": ["Dark"]},
    262: {"name": "Mightyena", "type": ["Dark"]},
    263: {"name": "Zigzagoon", "type": ["Normal"]},
    264: {"name": "Linoone", "type": ["Normal"]},
    265: {"name": "Wurmple", "type": ["Bug"]},
    266: {"name": "Silcoon", "type": ["Bug"]},
    267: {"name": "Beautifly", "type": ["Bug", "Flying"]},
    268: {"name": "Cascoon", "type": ["Bug"]},
    269: {"name": "Dustox", "type": ["Bug", "Poison"]},
    270: {"name": "Lotad", "type": ["Water", "Grass"]},
    271: {"name": "Lombre", "type": ["Water", "Grass"]},
    272: {"name": "Ludicolo", "type": ["Water", "Grass"]},
    273: {"name": "Seedot", "type": ["Grass"]},
    274: {"name": "Nuzleaf", "type": ["Grass", "Dark"]},
    275: {"name": "Shiftry", "type": ["Grass", "Dark"]},
    276: {"name": "Taillow", "type": ["Normal", "Flying"]},
    277: {"name": "Swellow", "type": ["Normal", "Flying"]},
    278: {"name": "Wingull", "type": ["Water", "Flying"]},
    279: {"name": "Pelipper", "type": ["Water", "Flying"]},
    280: {"name": "Ralts", "type": ["Psychic", "Fairy"]},
    281: {"name": "Kirlia", "type": ["Psychic", "Fairy"]},
    282: {"name": "Gardevoir", "type": ["Psychic", "Fairy"]},
    283: {"name": "Surskit", "type": ["Bug", "Water"]},
    284: {"name": "Masquerain", "type": ["Bug", "Flying"]},
    285: {"name": "Shroomish", "type": ["Grass"]},
    286: {"name": "Breloom", "type": ["Grass", "Fighting"]},
    287: {"name": "Slakoth", "type": ["Normal"]},
    288: {"name": "Vigoroth", "type": ["Normal"]},
    289: {"name": "Slaking", "type": ["Normal"]},
    290: {"name": "Nincada", "type": ["Bug", "Ground"]},
    291: {"name": "Ninjask", "type": ["Bug", "Flying"]},
    292: {"name": "Shedinja", "type": ["Bug", "Ghost"]},
    293: {"name": "Whismur", "type": ["Normal"]},
    294: {"name": "Loudred", "type": ["Normal"]},
    295: {"name": "Exploud", "type": ["Normal"]},
    296: {"name": "Makuhita", "type": ["Fighting"]},
    297: {"name": "Hariyama", "type": ["Fighting"]},
    298: {"name": "Azurill", "type": ["Normal", "Fairy"]},
    299: {"name": "Nosepass", "type": ["Rock"]},
    300: {"name": "Skitty", "type": ["Normal"]},
    301: {"name": "Delcatty", "type": ["Normal"]},
    302: {"name": "Sableye", "type": ["Dark", "Ghost"]},
    303: {"name": "Mawile", "type": ["Steel", "Fairy"]},
    304: {"name": "Aron", "type": ["Steel", "Rock"]},
    305: {"name": "Lairon", "type": ["Steel", "Rock"]},
    306: {"name": "Aggron", "type": ["Steel", "Rock"]},
    307: {"name": "Meditite", "type": ["Fighting", "Psychic"]},
    308: {"name": "Medicham", "type": ["Fighting", "Psychic"]},
    309: {"name": "Electrike", "type": ["Electric"]},
    310: {"name": "Manectric", "type": ["Electric"]},
    311: {"name": "Plusle", "type": ["Electric"]},
    312: {"name": "Minun", "type": ["Electric"]},
    313: {"name": "Volbeat", "type": ["Bug"]},
    314: {"name": "Illumise", "type": ["Bug"]},
    315: {"name": "Roselia", "type": ["Grass", "Poison"]},
    316: {"name": "Gulpin", "type": ["Poison"]},
    317: {"name": "Swalot", "type": ["Poison"]},
    318: {"name": "Carvanha", "type": ["Water", "Dark"]},
    319: {"name": "Sharpedo", "type": ["Water", "Dark"]},
    320: {"name": "Wailmer", "type": ["Water"]},
    321: {"name": "Wailord", "type": ["Water"]},
    322: {"name": "Numel", "type": ["Fire", "Ground"]},
    323: {"name": "Camerupt", "type": ["Fire", "Ground"]},
    324: {"name": "Torkoal", "type": ["Fire"]},
    325: {"name": "Spoink", "type": ["Psychic"]},
    326: {"name": "Grumpig", "type": ["Psychic"]},
    327: {"name": "Spinda", "type": ["Normal"]},
    328: {"name": "Trapinch", "type": ["Ground"]},
    329: {"name": "Vibrava", "type": ["Ground", "Dragon"]},
    330: {"name": "Flygon", "type": ["Ground", "Dragon"]},
    331: {"name": "Cacnea", "type": ["Grass"]},
    332: {"name": "Cacturne", "type": ["Grass", "Dark"]},
    333: {"name": "Swablu", "type": ["Normal", "Flying"]},
    334: {"name": "Altaria", "type": ["Dragon", "Flying"]},
    335: {"name": "Zangoose", "type": ["Normal"]},
    336: {"name": "Seviper", "type": ["Poison"]},
    337: {"name": "Lunatone", "type": ["Rock", "Psychic"]},
    338: {"name": "Solrock", "type": ["Rock", "Psychic"]},
    339: {"name": "Barboach", "type": ["Water", "Ground"]},
    340: {"name": "Whiscash", "type": ["Water", "Ground"]},
    341: {"name": "Corphish", "type": ["Water"]},
    342: {"name": "Crawdaunt", "type": ["Water", "Dark"]},
    343: {"name": "Baltoy", "type": ["Ground", "Psychic"]},
    344: {"name": "Claydol", "type": ["Ground", "Psychic"]},
    345: {"name": "Lileep", "type": ["Rock", "Grass"]},
    346: {"name": "Cradily", "type": ["Rock", "Grass"]},
    347: {"name": "Anorith", "type": ["Rock", "Bug"]},
    348: {"name": "Armaldo", "type": ["Rock", "Bug"]},
    349: {"name": "Feebas", "type": ["Water"]},
    350: {"name": "Milotic", "type": ["Water"]},
    351: {"name": "Castform", "type": ["Normal"]},
    352: {"name": "Kecleon", "type": ["Normal"]},
    353: {"name": "Shuppet", "type": ["Ghost"]},
    354: {"name": "Banette", "type": ["Ghost"]},
    355: {"name": "Duskull", "type": ["Ghost"]},
    356: {"name": "Dusclops", "type": ["Ghost"]},
    357: {"name": "Tropius", "type": ["Grass", "Flying"]},
    358: {"name": "Chimecho", "type": ["Psychic"]},
    359: {"name": "Absol", "type": ["Dark"]},
    360: {"name": "Wynaut", "type": ["Psychic"]},
    361: {"name": "Snorunt", "type": ["Ice"]},
    362: {"name": "Glalie", "type": ["Ice"]},
    363: {"name": "Spheal", "type": ["Ice", "Water"]},
    364: {"name": "Sealeo", "type": ["Ice", "Water"]},
    365: {"name": "Walrein", "type": ["Ice", "Water"]},
    366: {"name": "Clamperl", "type": ["Water"]},
    367: {"name": "Huntail", "type": ["Water"]},
    368: {"name": "Gorebyss", "type": ["Water"]},
    369: {"name": "Relicanth", "type": ["Water", "Rock"]},
    370: {"name": "Luvdisc", "type": ["Water"]},
    371: {"name": "Bagon", "type": ["Dragon"]},
    372: {"name": "Shelgon", "type": ["Dragon"]},
    373: {"name": "Salamence", "type": ["Dragon", "Flying"]},
    374: {"name": "Beldum", "type": ["Steel", "Psychic"]},
    375: {"name": "Metang", "type": ["Steel", "Psychic"]},
    376: {"name": "Metagross", "type": ["Steel", "Psychic"]},
    377: {"name": "Regirock", "type": ["Rock"]},
    378: {"name": "Regice", "type": ["Ice"]},
    379: {"name": "Registeel", "type": ["Steel"]},
    380: {"name": "Latias", "type": ["Dragon", "Psychic"]},
    381: {"name": "Latios", "type": ["Dragon", "Psychic"]},
    382: {"name": "Kyogre", "type": ["Water"]},
    383: {"name": "Groudon", "type": ["Ground"]},
    384: {"name": "Rayquaza", "type": ["Dragon", "Flying"]},
    385: {"name": "Jirachi", "type": ["Steel", "Psychic"]},
    386: {"name": "Deoxys", "type": ["Psychic"]},
    387: {"name": "Turtwig", "type": ["Grass"]},
    388: {"name": "Grotle", "type": ["Grass"]},
    389: {"name": "Torterra", "type": ["Grass", "Ground"]},
    390: {"name": "Chimchar", "type": ["Fire"]},
    391: {"name": "Monferno", "type": ["Fire", "Fighting"]},
    392: {"name": "Infernape", "type": ["Fire", "Fighting"]},
    393: {"name": "Piplup", "type": ["Water"]},
    394: {"name": "Prinplup", "type": ["Water"]},
    395: {"name": "Empoleon", "type": ["Water", "Steel"]},
    396: {"name": "Starly", "type": ["Normal", "Flying"]},
    397: {"name": "Staravia", "type": ["Normal", "Flying"]},
    398: {"name": "Staraptor", "type": ["Normal", "Flying"]},
    399: {"name": "Bidoof", "type": ["Normal"]},
    400: {"name": "Bibarel", "type": ["Normal", "Water"]},
    401: {"name": "Kricketot", "type": ["Bug"]},
    402: {"name": "Kricketune", "type": ["Bug"]},
    403: {"name": "Shinx", "type": ["Electric"]},
    404: {"name": "Luxio", "type": ["Electric"]},
    405: {"name": "Luxray", "type": ["Electric"]},
    406: {"name": "Budew", "type": ["Grass", "Poison"]},
    407: {"name": "Roserade", "type": ["Grass", "Poison"]},
    408: {"name": "Cranidos", "type": ["Rock"]},
    409: {"name": "Rampardos", "type": ["Rock"]},
    410: {"name": "Shieldon", "type": ["Rock", "Steel"]},
    411: {"name": "Bastiodon", "type": ["Rock", "Steel"]},
    412: {"name": "Burmy", "type": ["Bug"]},
    413: {"name": "Wormadam", "type": ["Bug", "Grass"]},
    414: {"name": "Mothim", "type": ["Bug", "Flying"]},
    415: {"name": "Combee", "type": ["Bug", "Flying"]},
    416: {"name": "Vespiquen", "type": ["Bug", "Flying"]},
    417: {"name": "Pachirisu", "type": ["Electric"]},
    418: {"name": "Buizel", "type": ["Water"]},
    419: {"name": "Floatzel", "type": ["Water"]},
    420: {"name": "Cherubi", "type": ["Grass"]},
    421: {"name": "Cherrim", "type": ["Grass"]},
    422: {"name": "Shellos", "type": ["Water"]},
    423: {"name": "Gastrodon", "type": ["Water", "Ground"]},
    424: {"name": "Ambipom", "type": ["Normal"]},
    425: {"name": "Drifloon", "type": ["Ghost", "Flying"]},
    426: {"name": "Drifblim", "type": ["Ghost", "Flying"]},
    427: {"name": "Buneary", "type": ["Normal"]},
    428: {"name": "Lopunny", "type": ["Normal"]},
    429: {"name": "Mismagius", "type": ["Ghost"]},
    430: {"name": "Honchkrow", "type": ["Dark", "Flying"]},
    431: {"name": "Glameow", "type": ["Normal"]},
    432: {"name": "Purugly", "type": ["Normal"]},
    433: {"name": "Chingling", "type": ["Psychic"]},
    434: {"name": "Stunky", "type": ["Poison", "Dark"]},
    435: {"name": "Skuntank", "type": ["Poison", "Dark"]},
    436: {"name": "Bronzor", "type": ["Steel", "Psychic"]},
    437: {"name": "Bronzong", "type": ["Steel", "Psychic"]},
    438: {"name": "Bonsly", "type": ["Rock"]},
    439: {"name": "Mime Jr.", "type": ["Psychic", "Fairy"]},
    440: {"name": "Happiny", "type": ["Normal"]},
    441: {"name": "Chatot", "type": ["Normal", "Flying"]},
    442: {"name": "Spiritomb", "type": ["Ghost", "Dark"]},
    443: {"name": "Gible", "type": ["Dragon", "Ground"]},
    444: {"name": "Gabite", "type": ["Dragon", "Ground"]},
    445: {"name": "Garchomp", "type": ["Dragon", "Ground"]},
    446: {"name": "Munchlax", "type": ["Normal"]},
    447: {"name": "Riolu", "type": ["Fighting"]},
    448: {"name": "Lucario", "type": ["Fighting", "Steel"]},
    449: {"name": "Hippopotas", "type": ["Ground"]},
    450: {"name": "Hippowdon", "type": ["Ground"]},
    451: {"name": "Skorupi", "type": ["Poison", "Bug"]},
    452: {"name": "Drapion", "type": ["Poison", "Dark"]},
    453: {"name": "Croagunk", "type": ["Poison", "Fighting"]},
    454: {"name": "Toxicroak", "type": ["Poison", "Fighting"]},
    455: {"name": "Carnivine", "type": ["Grass"]},
    456: {"name": "Finneon", "type": ["Water"]},
    457: {"name": "Lumineon", "type": ["Water"]},
    458: {"name": "Mantyke", "type": ["Water", "Flying"]},
    459: {"name": "Snover", "type": ["Grass", "Ice"]},
    460: {"name": "Abomasnow", "type": ["Grass", "Ice"]},
    461: {"name": "Weavile", "type": ["Dark", "Ice"]},
    462: {"name": "Magnezone", "type": ["Electric", "Steel"]},
    463: {"name": "Lickilicky", "type": ["Normal"]},
    464: {"name": "Rhyperior", "type": ["Ground", "Rock"]},
    465: {"name": "Tangrowth", "type": ["Grass"]},
    466: {"name": "Electivire", "type": ["Electric"]},
    467: {"name": "Magmortar", "type": ["Fire"]},
    468: {"name": "Togekiss", "type": ["Fairy", "Flying"]},
    469: {"name": "Yanmega", "type": ["Bug", "Flying"]},
    470: {"name": "Leafeon", "type": ["Grass"]},
    471: {"name": "Glaceon", "type": ["Ice"]},
    472: {"name": "Gliscor", "type": ["Ground", "Flying"]},
    473: {"name": "Mamoswine", "type": ["Ice", "Ground"]},
    474: {"name": "Porygon-Z", "type": ["Normal"]},
    475: {"name": "Gallade", "type": ["Psychic", "Fighting"]},
    476: {"name": "Probopass", "type": ["Rock", "Steel"]},
    477: {"name": "Dusknoir", "type": ["Ghost"]},
    478: {"name": "Froslass", "type": ["Ice", "Ghost"]},
    479: {"name": "Rotom", "type": ["Electric", "Ghost"]},
    480: {"name": "Uxie", "type": ["Psychic"]},
    481: {"name": "Mesprit", "type": ["Psychic"]},
    482: {"name": "Azelf", "type": ["Psychic"]},
    483: {"name": "Dialga", "type": ["Steel", "Dragon"]},
    484: {"name": "Palkia", "type": ["Water", "Dragon"]},
    485: {"name": "Heatran", "type": ["Fire", "Steel"]},
    486: {"name": "Regigigas", "type": ["Normal"]},
    487: {"name": "Giratina", "type": ["Ghost", "Dragon"]},
    488: {"name": "Cresselia", "type": ["Psychic"]},
    489: {"name": "Phione", "type": ["Water"]},
    490: {"name": "Manaphy", "type": ["Water"]},
    491: {"name": "Darkrai", "type": ["Dark"]},
    492: {"name": "Shaymin", "type": ["Grass"]},
    493: {"name": "Arceus", "type": ["Normal"]},
    494: {"name": "Victini", "type": ["Psychic", "Fire"]},
    495: {"name": "Snivy", "type": ["Grass"]},
    496: {"name": "Servine", "type": ["Grass"]},
    497: {"name": "Serperior", "type": ["Grass"]},
    498: {"name": "Tepig", "type": ["Fire"]},
    499: {"name": "Pignite", "type": ["Fire", "Fighting"]},
    500: {"name": "Emboar", "type": ["Fire", "Fighting"]},
    501: {"name": "Oshawott", "type": ["Water"]},
    502: {"name": "Dewott", "type": ["Water"]},
    503: {"name": "Samurott", "type": ["Water"]},
    504: {"name": "Patrat", "type": ["Normal"]},
    505: {"name": "Watchog", "type": ["Normal"]},
    506: {"name": "Lillipup", "type": ["Normal"]},
    507: {"name": "Herdier", "type": ["Normal"]},
    508: {"name": "Stoutland", "type": ["Normal"]},
    509: {"name": "Purrloin", "type": ["Dark"]},
    510: {"name": "Liepard", "type": ["Dark"]},
    511: {"name": "Pansage", "type": ["Grass"]},
    512: {"name": "Simisage", "type": ["Grass"]},
    513: {"name": "Pansear", "type": ["Fire"]},
    514: {"name": "Simisear", "type": ["Fire"]},
    515: {"name": "Panpour", "type": ["Water"]},
    516: {"name": "Simipour", "type": ["Water"]},
    517: {"name": "Munna", "type": ["Psychic"]},
    518: {"name": "Musharna", "type": ["Psychic"]},
    519: {"name": "Pidove", "type": ["Normal", "Flying"]},
    520: {"name": "Tranquill", "type": ["Normal", "Flying"]},
    521: {"name": "Unfezant", "type": ["Normal", "Flying"]},
    522: {"name": "Blitzle", "type": ["Electric"]},
    523: {"name": "Zebstrika", "type": ["Electric"]},
    524: {"name": "Roggenrola", "type": ["Rock"]},
    525: {"name": "Boldore", "type": ["Rock"]},
    526: {"name": "Gigalith", "type": ["Rock"]},
    527: {"name": "Woobat", "type": ["Psychic", "Flying"]},
    528: {"name": "Swoobat", "type": ["Psychic", "Flying"]},
    529: {"name": "Drilbur", "type": ["Ground"]},
    530: {"name": "Excadrill", "type": ["Ground", "Steel"]},
    531: {"name": "Audino", "type": ["Normal"]},
    532: {"name": "Timburr", "type": ["Fighting"]},
    533: {"name": "Gurdurr", "type": ["Fighting"]},
    534: {"name": "Conkeldurr", "type": ["Fighting"]},
    535: {"name": "Tympole", "type": ["Water"]},
    536: {"name": "Palpitoad", "type": ["Water", "Ground"]},
    537: {"name": "Seismitoad", "type": ["Water", "Ground"]},
    538: {"name": "Throh", "type": ["Fighting"]},
    539: {"name": "Sawk", "type": ["Fighting"]},
    540: {"name": "Sewaddle", "type": ["Bug", "Grass"]},
    541: {"name": "Swadloon", "type": ["Bug", "Grass"]},
    542: {"name": "Leavanny", "type": ["Bug", "Grass"]},
    543: {"name": "Venipede", "type": ["Bug", "Poison"]},
    544: {"name": "Whirlipede", "type": ["Bug", "Poison"]},
    545: {"name": "Scolipede", "type": ["Bug", "Poison"]},
    546: {"name": "Cottonee", "type": ["Grass", "Fairy"]},
    547: {"name": "Whimsicott", "type": ["Grass", "Fairy"]},
    548: {"name": "Petilil", "type": ["Grass"]},
    549: {"name": "Lilligant", "type": ["Grass"]},
    550: {"name": "Basculin", "type": ["Water"]},
    551: {"name": "Sandile", "type": ["Ground", "Dark"]},
    552: {"name": "Krokorok", "type": ["Ground", "Dark"]},
    553: {"name": "Krookodile", "type": ["Ground", "Dark"]},
    554: {"name": "Darumaka", "type": ["Fire"]},
    555: {"name": "Darmanitan", "type": ["Fire"]},
    556: {"name": "Maractus", "type": ["Grass"]},
    557: {"name": "Dwebble", "type": ["Bug", "Rock"]},
    558: {"name": "Crustle", "type": ["Bug", "Rock"]},
    559: {"name": "Scraggy", "type": ["Dark", "Fighting"]},
    560: {"name": "Scrafty", "type": ["Dark", "Fighting"]},
    561: {"name": "Sigilyph", "type": ["Psychic", "Flying"]},
    562: {"name": "Yamask", "type": ["Ghost"]},
    563: {"name": "Cofagrigus", "type": ["Ghost"]},
    564: {"name": "Tirtouga", "type": ["Water", "Rock"]},
    565: {"name": "Carracosta", "type": ["Water", "Rock"]},
    566: {"name": "Archen", "type": ["Rock", "Flying"]},
    567: {"name": "Archeops", "type": ["Rock", "Flying"]},
    568: {"name": "Trubbish", "type": ["Poison"]},
    569: {"name": "Garbodor", "type": ["Poison"]},
    570: {"name": "Zorua", "type": ["Dark"]},
    571: {"name": "Zoroark", "type": ["Dark"]},
    572: {"name": "Minccino", "type": ["Normal"]},
    573: {"name": "Cinccino", "type": ["Normal"]},
    574: {"name": "Gothita", "type": ["Psychic"]},
    575: {"name": "Gothorita", "type": ["Psychic"]},
    576: {"name": "Gothitelle", "type": ["Psychic"]},
    577: {"name": "Solosis", "type": ["Psychic"]},
    578: {"name": "Duosion", "type": ["Psychic"]},
    579: {"name": "Reuniclus", "type": ["Psychic"]},
    580: {"name": "Ducklett", "type": ["Water", "Flying"]},
    581: {"name": "Swanna", "type": ["Water", "Flying"]},
    582: {"name": "Vanillite", "type": ["Ice"]},
    583: {"name": "Vanillish", "type": ["Ice"]},
    584: {"name": "Vanilluxe", "type": ["Ice"]},
    585: {"name": "Deerling", "type": ["Normal", "Grass"]},
    586: {"name": "Sawsbuck", "type": ["Normal", "Grass"]},
    587: {"name": "Emolga", "type": ["Electric", "Flying"]},
    588: {"name": "Karrablast", "type": ["Bug"]},
    589: {"name": "Escavalier", "type": ["Bug", "Steel"]},
    590: {"name": "Foongus", "type": ["Grass", "Poison"]},
    591: {"name": "Amoonguss", "type": ["Grass", "Poison"]},
    592: {"name": "Frillish", "type": ["Water", "Ghost"]},
    593: {"name": "Jellicent", "type": ["Water", "Ghost"]},
    594: {"name": "Alomomola", "type": ["Water"]},
    595: {"name": "Joltik", "type": ["Bug", "Electric"]},
    596: {"name": "Galvantula", "type": ["Bug", "Electric"]},
    597: {"name": "Ferroseed", "type": ["Grass", "Steel"]},
    598: {"name": "Ferrothorn", "type": ["Grass", "Steel"]},
    599: {"name": "Klink", "type": ["Steel"]},
    600: {"name": "Klang", "type": ["Steel"]},
    601: {"name": "Klinklang", "type": ["Steel"]},
    602: {"name": "Tynamo", "type": ["Electric"]},
    603: {"name": "Eelektrik", "type": ["Electric"]},
    604: {"name": "Eelektross", "type": ["Electric"]},
    605: {"name": "Elgyem", "type": ["Psychic"]},
    606: {"name": "Beheeyem", "type": ["Psychic"]},
    607: {"name": "Litwick", "type": ["Ghost", "Fire"]},
    608: {"name": "Lampent", "type": ["Ghost", "Fire"]},
    609: {"name": "Chandelure", "type": ["Ghost", "Fire"]},
    610: {"name": "Axew", "type": ["Dragon"]},
    611: {"name": "Fraxure", "type": ["Dragon"]},
    612: {"name": "Haxorus", "type": ["Dragon"]},
    613: {"name": "Cubchoo", "type": ["Ice"]},
    614: {"name": "Beartic", "type": ["Ice"]},
    615: {"name": "Cryogonal", "type": ["Ice"]},
    616: {"name": "Shelmet", "type": ["Bug"]},
    617: {"name": "Accelgor", "type": ["Bug"]},
    618: {"name": "Stunfisk", "type": ["Ground", "Electric"]},
    619: {"name": "Mienfoo", "type": ["Fighting"]},
    620: {"name": "Mienshao", "type": ["Fighting"]},
    621: {"name": "Druddigon", "type": ["Dragon"]},
    622: {"name": "Golett", "type": ["Ground", "Ghost"]},
    623: {"name": "Golurk", "type": ["Ground", "Ghost"]},
    624: {"name": "Pawniard", "type": ["Dark", "Steel"]},
    625: {"name": "Bisharp", "type": ["Dark", "Steel"]},
    626: {"name": "Bouffalant", "type": ["Normal"]},
    627: {"name": "Rufflet", "type": ["Normal", "Flying"]},
    628: {"name": "Braviary", "type": ["Normal", "Flying"]},
    629: {"name": "Vullaby", "type": ["Dark", "Flying"]},
    630: {"name": "Mandibuzz", "type": ["Dark", "Flying"]},
    631: {"name": "Heatmor", "type": ["Fire"]},
    632: {"name": "Durant", "type": ["Bug", "Steel"]},
    633: {"name": "Deino", "type": ["Dark", "Dragon"]},
    634: {"name": "Zweilous", "type": ["Dark", "Dragon"]},
    635: {"name": "Hydreigon", "type": ["Dark", "Dragon"]},
    636: {"name": "Larvesta", "type": ["Bug", "Fire"]},
    637: {"name": "Volcarona", "type": ["Bug", "Fire"]},
    638: {"name": "Cobalion", "type": ["Steel", "Fighting"]},
    639: {"name": "Terrakion", "type": ["Rock", "Fighting"]},
    640: {"name": "Virizion", "type": ["Grass", "Fighting"]},
    641: {"name": "Tornadus", "type": ["Flying"]},
    642: {"name": "Thundurus", "type": ["Electric", "Flying"]},
    643: {"name": "Reshiram", "type": ["Dragon", "Fire"]},
    644: {"name": "Zekrom", "type": ["Dragon", "Electric"]},
    645: {"name": "Landorus", "type": ["Ground", "Flying"]},
    646: {"name": "Kyurem", "type": ["Dragon", "Ice"]},
    647: {"name": "Keldeo", "type": ["Water", "Fighting"]},
    648: {"name": "Meloetta", "type": ["Normal", "Psychic"]},
    649: {"name": "Genesect", "type": ["Bug", "Steel"]},
    650: {"name": "Chespin", "type": ["Grass"]},
    651: {"name": "Quilladin", "type": ["Grass"]},
    652: {"name": "Chesnaught", "type": ["Grass", "Fighting"]},
    653: {"name": "Fennekin", "type": ["Fire"]},
    654: {"name": "Braixen", "type": ["Fire"]},
    655: {"name": "Delphox", "type": ["Fire", "Psychic"]},
    656: {"name": "Froakie", "type": ["Water"]},
    657: {"name": "Frogadier", "type": ["Water"]},
    658: {"name": "Greninja", "type": ["Water", "Dark"]},
    659: {"name": "Bunnelby", "type": ["Normal"]},
    660: {"name": "Diggersby", "type": ["Normal", "Ground"]},
    661: {"name": "Fletchling", "type": ["Normal", "Flying"]},
    662: {"name": "Fletchinder", "type": ["Fire", "Flying"]},
    663: {"name": "Talonflame", "type": ["Fire", "Flying"]},
    664: {"name": "Scatterbug", "type": ["Bug"]},
    665: {"name": "Spewpa", "type": ["Bug"]},
    666: {"name": "Vivillon", "type": ["Bug", "Flying"]},
    667: {"name": "Litleo", "type": ["Fire", "Normal"]},
    668: {"name": "Pyroar", "type": ["Fire", "Normal"]},
    669: {"name": "Flabébé", "type": ["Fairy"]},
    670: {"name": "Floette", "type": ["Fairy"]},
    671: {"name": "Florges", "type": ["Fairy"]},
    672: {"name": "Skiddo", "type": ["Grass"]},
    673: {"name": "Gogoat", "type": ["Grass"]},
    674: {"name": "Pancham", "type": ["Fighting"]},
    675: {"name": "Pangoro", "type": ["Fighting", "Dark"]},
    676: {"name": "Furfrou", "type": ["Normal"]},
    677: {"name": "Espurr", "type": ["Psychic"]},
    678: {"name": "Meowstic", "type": ["Psychic"]},
    679: {"name": "Honedge", "type": ["Steel", "Ghost"]},
    680: {"name": "Doublade", "type": ["Steel", "Ghost"]},
    681: {"name": "Aegislash", "type": ["Steel", "Ghost"]},
    682: {"name": "Spritzee", "type": ["Fairy"]},
    683: {"name": "Aromatisse", "type": ["Fairy"]},
    684: {"name": "Swirlix", "type": ["Fairy"]},
    685: {"name": "Slurpuff", "type": ["Fairy"]},
    686: {"name": "Inkay", "type": ["Dark", "Psychic"]},
    687: {"name": "Malamar", "type": ["Dark", "Psychic"]},
    688: {"name": "Binacle", "type": ["Rock", "Water"]},
    689: {"name": "Barbaracle", "type": ["Rock", "Water"]},
    690: {"name": "Skrelp", "type": ["Poison", "Water"]},
    691: {"name": "Dragalge", "type": ["Poison", "Dragon"]},
    692: {"name": "Clauncher", "type": ["Water"]},
    693: {"name": "Clawitzer", "type": ["Water"]},
    694: {"name": "Helioptile", "type": ["Electric", "Normal"]},
    695: {"name": "Heliolisk", "type": ["Electric", "Normal"]},
    696: {"name": "Tyrunt", "type": ["Rock", "Dragon"]},
    697: {"name": "Tyrantrum", "type": ["Rock", "Dragon"]},
    698: {"name": "Amaura", "type": ["Rock", "Ice"]},
    699: {"name": "Aurorus", "type": ["Rock", "Ice"]},
    700: {"name": "Sylveon", "type": ["Fairy"]},
    701: {"name": "Hawlucha", "type": ["Fighting", "Flying"]},
    702: {"name": "Dedenne", "type": ["Electric", "Fairy"]},
    703: {"name": "Carbink", "type": ["Rock", "Fairy"]},
    704: {"name": "Goomy", "type": ["Dragon"]},
    705: {"name": "Sliggoo", "type": ["Dragon"]},
    706: {"name": "Goodra", "type": ["Dragon"]},
    707: {"name": "Klefki", "type": ["Steel", "Fairy"]},
    708: {"name": "Phantump", "type": ["Ghost", "Grass"]},
    709: {"name": "Trevenant", "type": ["Ghost", "Grass"]},
    710: {"name": "Pumpkaboo", "type": ["Ghost", "Grass"]},
    711: {"name": "Gourgeist", "type": ["Ghost", "Grass"]},
    712: {"name": "Bergmite", "type": ["Ice"]},
    713: {"name": "Avalugg", "type": ["Ice"]},
    714: {"name": "Noibat", "type": ["Flying", "Dragon"]},
    715: {"name": "Noivern", "type": ["Flying", "Dragon"]},
    716: {"name": "Xerneas", "type": ["Fairy"]},
    717: {"name": "Yveltal", "type": ["Dark", "Flying"]},
    718: {"name": "Zygarde", "type": ["Dragon", "Ground"]},
    719: {"name": "Diancie", "type": ["Rock", "Fairy"]},
    720: {"name": "Hoopa", "type": ["Psychic", "Ghost"]},
    721: {"name": "Volcanion", "type": ["Fire", "Water"]},
    722: {"name": "Rowlet", "type": ["Grass", "Flying"]},
    723: {"name": "Dartrix", "type": ["Grass", "Flying"]},
    724: {"name": "Decidueye", "type": ["Grass", "Ghost"]},
    725: {"name": "Litten", "type": ["Fire"]},
    726: {"name": "Torracat", "type": ["Fire"]},
    727: {"name": "Incineroar", "type": ["Fire", "Dark"]},
    728: {"name": "Popplio", "type": ["Water"]},
    729: {"name": "Brionne", "type": ["Water"]},
    730: {"name": "Primarina", "type": ["Water", "Fairy"]},
    731: {"name": "Pikipek", "type": ["Normal", "Flying"]},
    732: {"name": "Trumbeak", "type": ["Normal", "Flying"]},
    733: {"name": "Toucannon", "type": ["Normal", "Flying"]},
    734: {"name": "Yungoos", "type": ["Normal"]},
    735: {"name": "Gumshoos", "type": ["Normal"]},
    736: {"name": "Grubbin", "type": ["Bug"]},
    737: {"name": "Charjabug", "type": ["Bug", "Electric"]},
    738: {"name": "Vikavolt", "type": ["Bug", "Electric"]},
    739: {"name": "Crabrawler", "type": ["Fighting"]},
    740: {"name": "Crabominable", "type": ["Fighting", "Ice"]},
    741: {"name": "Oricorio", "type": ["Fire", "Flying"]},
    742: {"name": "Cutiefly", "type": ["Bug", "Fairy"]},
    743: {"name": "Ribombee", "type": ["Bug", "Fairy"]},
    744: {"name": "Rockruff", "type": ["Rock"]},
    745: {"name": "Lycanroc", "type": ["Rock"]},
    746: {"name": "Wishiwashi", "type": ["Water"]},
    747: {"name": "Mareanie", "type": ["Poison", "Water"]},
    748: {"name": "Toxapex", "type": ["Poison", "Water"]},
    749: {"name": "Mudbray", "type": ["Ground"]},
    750: {"name": "Mudsdale", "type": ["Ground"]},
    751: {"name": "Dewpider", "type": ["Water", "Bug"]},
    752: {"name": "Araquanid", "type": ["Water", "Bug"]},
    753: {"name": "Fomantis", "type": ["Grass"]},
    754: {"name": "Lurantis", "type": ["Grass"]},
    755: {"name": "Morelull", "type": ["Grass", "Fairy"]},
    756: {"name": "Shiinotic", "type": ["Grass", "Fairy"]},
    757: {"name": "Salandit", "type": ["Poison", "Fire"]},
    758: {"name": "Salazzle", "type": ["Poison", "Fire"]},
    759: {"name": "Stufful", "type": ["Normal", "Fighting"]},
    760: {"name": "Bewear", "type": ["Normal", "Fighting"]},
    761: {"name": "Bounsweet", "type": ["Grass"]},
    762: {"name": "Steenee", "type": ["Grass"]},
    763: {"name": "Tsareena", "type": ["Grass"]},
    764: {"name": "Comfey", "type": ["Fairy"]},
    765: {"name": "Oranguru", "type": ["Normal", "Psychic"]},
    766: {"name": "Passimian", "type": ["Fighting"]},
    767: {"name": "Wimpod", "type": ["Bug", "Water"]},
    768: {"name": "Golisopod", "type": ["Bug", "Water"]},
    769: {"name": "Sandygast", "type": ["Ghost", "Ground"]},
    770: {"name": "Palossand", "type": ["Ghost", "Ground"]},
    771: {"name": "Pyukumuku", "type": ["Water"]},
    772: {"name": "Type: Null", "type": ["Normal"]},
    773: {"name": "Silvally", "type": ["Normal"]},
    774: {"name": "Minior", "type": ["Rock", "Flying"]},
    775: {"name": "Komala", "type": ["Normal"]},
    776: {"name": "Turtonator", "type": ["Fire", "Dragon"]},
    777: {"name": "Togedemaru", "type": ["Electric", "Steel"]},
    778: {"name": "Mimikyu", "type": ["Ghost", "Fairy"]},
    779: {"name": "Bruxish", "type": ["Water", "Psychic"]},
    780: {"name": "Drampa", "type": ["Normal", "Dragon"]},
    781: {"name": "Dhelmise", "type": ["Ghost", "Grass"]},
    782: {"name": "Jangmo-o", "type": ["Dragon"]},
    783: {"name": "Hakamo-o", "type": ["Dragon", "Fighting"]},
    784: {"name": "Kommo-o", "type": ["Dragon", "Fighting"]},
    785: {"name": "Tapu Koko", "type": ["Electric", "Fairy"]},
    786: {"name": "Tapu Lele", "type": ["Psychic", "Fairy"]},
    787: {"name": "Tapu Bulu", "type": ["Grass", "Fairy"]},
    788: {"name": "Tapu Fini", "type": ["Water", "Fairy"]},
    789: {"name": "Cosmog", "type": ["Psychic"]},
    790: {"name": "Cosmoem", "type": ["Psychic"]},
    791: {"name": "Solgaleo", "type": ["Psychic", "Steel"]},
    792: {"name": "Lunala", "type": ["Psychic", "Ghost"]},
    793: {"name": "Nihilego", "type": ["Rock", "Poison"]},
    794: {"name": "Buzzwole", "type": ["Bug", "Fighting"]},
    795: {"name": "Pheromosa", "type": ["Bug", "Fighting"]},
    796: {"name": "Xurkitree", "type": ["Electric"]},
    797: {"name": "Celesteela", "type": ["Steel", "Flying"]},
    798: {"name": "Kartana", "type": ["Grass", "Steel"]},
    799: {"name": "Guzzlord", "type": ["Dark", "Dragon"]},
    800: {"name": "Necrozma", "type": ["Psychic"]},
    801: {"name": "Magearna", "type": ["Steel", "Fairy"]},
    802: {"name": "Marshadow", "type": ["Fighting", "Ghost"]},
    803: {"name": "Poipole", "type": ["Poison"]},
    804: {"name": "Naganadel", "type": ["Poison", "Dragon"]},
    805: {"name": "Stakataka", "type": ["Rock", "Steel"]},
    806: {"name": "Blacephalon", "type": ["Fire", "Ghost"]},
    807: {"name": "Zeraora", "type": ["Electric"]},
    808: {"name": "Meltan", "type": ["Steel"]},
    809: {"name": "Melmetal", "type": ["Steel"]},
    810: {"name": "Grookey", "type": ["Grass"]},
    811: {"name": "Thwackey", "type": ["Grass"]},
    812: {"name": "Rillaboom", "type": ["Grass"]},
    813: {"name": "Scorbunny", "type": ["Fire"]},
    814: {"name": "Raboot", "type": ["Fire"]},
    815: {"name": "Cinderace", "type": ["Fire"]},
    816: {"name": "Sobble", "type": ["Water"]},
    817: {"name": "Drizzile", "type": ["Water"]},
    818: {"name": "Inteleon", "type": ["Water"]},
    819: {"name": "Skwovet", "type": ["Normal"]},
    820: {"name": "Greedent", "type": ["Normal"]},
    821: {"name": "Rookidee", "type": ["Flying"]},
    822: {"name": "Corvisquire", "type": ["Flying"]},
    823: {"name": "Corviknight", "type": ["Flying", "Steel"]},
    824: {"name": "Blipbug", "type": ["Bug"]},
    825: {"name": "Dottler", "type": ["Bug", "Psychic"]},
    826: {"name": "Orbeetle", "type": ["Bug", "Psychic"]},
    827: {"name": "Nickit", "type": ["Dark"]},
    828: {"name": "Thievul", "type": ["Dark"]},
    829: {"name": "Gossifleur", "type": ["Grass"]},
    830: {"name": "Eldegoss", "type": ["Grass"]},
    831: {"name": "Wooloo", "type": ["Normal"]},
    832: {"name": "Dubwool", "type": ["Normal"]},
    833: {"name": "Chewtle", "type": ["Water"]},
    834: {"name": "Drednaw", "type": ["Water", "Rock"]},
    835: {"name": "Yamper", "type": ["Electric"]},
    836: {"name": "Boltund", "type": ["Electric"]},
    837: {"name": "Rolycoly", "type": ["Rock"]},
    838: {"name": "Carkol", "type": ["Rock", "Fire"]},
    839: {"name": "Coalossal", "type": ["Rock", "Fire"]},
    840: {"name": "Applin", "type": ["Grass", "Dragon"]},
    841: {"name": "Flapple", "type": ["Grass", "Dragon"]},
    842: {"name": "Appletun", "type": ["Grass", "Dragon"]},
    843: {"name": "Silicobra", "type": ["Ground"]},
    844: {"name": "Sandaconda", "type": ["Ground"]},
    845: {"name": "Cramorant", "type": ["Flying", "Water"]},
    846: {"name": "Arrokuda", "type": ["Water"]},
    847: {"name": "Barraskewda", "type": ["Water"]},
    848: {"name": "Toxel", "type": ["Electric", "Poison"]},
    849: {"name": "Toxtricity", "type": ["Electric", "Poison"]},
    850: {"name": "Sizzlipede", "type": ["Fire", "Bug"]},
    851: {"name": "Centiskorch", "type": ["Fire", "Bug"]},
    852: {"name": "Clobbopus", "type": ["Fighting"]},
    853: {"name": "Grapploct", "type": ["Fighting"]},
    854: {"name": "Sinistea", "type": ["Ghost"]},
    855: {"name": "Polteageist", "type": ["Ghost"]},
    856: {"name": "Hatenna", "type": ["Psychic"]},
    857: {"name": "Hattrem", "type": ["Psychic"]},
    858: {"name": "Hatterene", "type": ["Psychic", "Fairy"]},
    859: {"name": "Impidimp", "type": ["Dark", "Fairy"]},
    860: {"name": "Morgrem", "type": ["Dark", "Fairy"]},
    861: {"name": "Grimmsnarl", "type": ["Dark", "Fairy"]},
    862: {"name": "Obstagoon", "type": ["Dark", "Normal"]},
    863: {"name": "Perrserker", "type": ["Steel"]},
    864: {"name": "Cursola", "type": ["Ghost"]},
    865: {"name": "Sirfetch'd", "type": ["Fighting"]},
    866: {"name": "Mr. Rime", "type": ["Ice", "Psychic"]},
    867: {"name": "Runerigus", "type": ["Ground", "Ghost"]},
    868: {"name": "Milcery", "type": ["Fairy"]},
    869: {"name": "Alcremie", "type": ["Fairy"]},
    870: {"name": "Falinks", "type": ["Fighting"]},
    871: {"name": "Pincurchin", "type": ["Electric"]},
    872: {"name": "Snom", "type": ["Ice", "Bug"]},
    873: {"name": "Frosmoth", "type": ["Ice", "Bug"]},
    874: {"name": "Stonjourner", "type": ["Rock"]},
    875: {"name": "Eiscue", "type": ["Ice"]},
    876: {"name": "Indeedee", "type": ["Psychic", "Normal"]},
    877: {"name": "Morpeko", "type": ["Electric", "Dark"]},
    878: {"name": "Cufant", "type": ["Steel"]},
    879: {"name": "Copperajah", "type": ["Steel"]},
    880: {"name": "Dracozolt", "type": ["Electric", "Dragon"]},
    881: {"name": "Arctozolt", "type": ["Electric", "Ice"]},
    882: {"name": "Dracovish", "type": ["Water", "Dragon"]},
    883: {"name": "Arctovish", "type": ["Water", "Ice"]},
    884: {"name": "Duraludon", "type": ["Steel", "Dragon"]},
    885: {"name": "Dreepy", "type": ["Dragon", "Ghost"]},
    886: {"name": "Drakloak", "type": ["Dragon", "Ghost"]},
    887: {"name": "Dragapult", "type": ["Dragon", "Ghost"]},
    888: {"name": "Zacian", "type": ["Fairy"]},
    889: {"name": "Zamazenta", "type": ["Fighting"]},
    890: {"name": "Eternatus", "type": ["Poison", "Dragon"]},
    891: {"name": "Kubfu", "type": ["Fighting"]},
    892: {"name": "Urshifu", "type": ["Fighting", "Dark"]},
    893: {"name": "Zarude", "type": ["Dark", "Grass"]},
    894: {"name": "Regieleki", "type": ["Electric"]},
    895: {"name": "Regidrago", "type": ["Dragon"]},
    896: {"name": "Glastrier", "type": ["Ice"]},
    897: {"name": "Spectrier", "type": ["Ghost"]},
    898: {"name": "Calyrex", "type": ["Psychic", "Grass"]},
    899: {"name": "Wyrdeer", "type": ["Normal", "Psychic"]},
    900: {"name": "Kleavor", "type": ["Bug", "Rock"]},
    901: {"name": "Ursaluna", "type": ["Ground", "Normal"]},
    902: {"name": "Basculegion", "type": ["Water", "Ghost"]},
    903: {"name": "Sneasler", "type": ["Fighting", "Poison"]},
    904: {"name": "Overqwil", "type": ["Dark", "Poison"]},
    905: {"name": "Enamorus", "type": ["Fairy", "Flying"]},
    906: {"name": "Sprigatito", "type": ["Grass"]},
    907: {"name": "Floragato", "type": ["Grass"]},
    908: {"name": "Meowscarada", "type": ["Grass", "Dark"]},
    909: {"name": "Fuecoco", "type": ["Fire"]},
    910: {"name": "Crocalor", "type": ["Fire"]},
    911: {"name": "Skeledirge", "type": ["Fire", "Ghost"]},
    912: {"name": "Quaxly", "type": ["Water"]},
    913: {"name": "Quaxwell", "type": ["Water"]},
    914: {"name": "Quaquaval", "type": ["Water", "Fighting"]},
    915: {"name": "Lechonk", "type": ["Normal"]},
    916: {"name": "Oinkologne", "type": ["Normal"]},
    917: {"name": "Tarountula", "type": ["Bug"]},
    918: {"name": "Spidops", "type": ["Bug"]},
    919: {"name": "Nymble", "type": ["Bug"]},
    920: {"name": "Lokix", "type": ["Big", "Dark"]},
    921: {"name": "Pawmi", "type": ["Electric"]},
    922: {"name": "Pawmo", "type": ["Electric", "Fighting"]},
    923: {"name": "Pawmot", "type": ["Electric", "Fighting"]},
    924: {"name": "Tandemaus", "type": ["Normal"]},
    925: {"name": "Maushold", "type": ["Normal"]},
    926: {"name": "Fidough", "type": ["Fairy"]},
    927: {"name": "Dachsbun", "type": ["Fairy"]},
    928: {"name": "Smoliv", "type": ["Grass", "Normal"]},
    929: {"name": "Dolliv", "type": ["Grass", "Normal"]},
    930: {"name": "Arboliva", "type": ["Grass", "Normal"]},
    931: {"name": "Squawkabilly", "type": ["Normal", "Flying"]},
    932: {"name": "Nacli", "type": ["Rock"]},
    933: {"name": "Naclstack", "type": ["Rock"]},
    934: {"name": "Garganacl", "type": ["Rock"]},
    935: {"name": "Charcadet", "type": ["Fire"]},
    936: {"name": "Armarouge", "type": ["Fire", "Psychic"]},
    937: {"name": "Ceruledge", "type": ["Fire", "Ghost"]},
    938: {"name": "Tadbulb", "type": ["Electric"]},
    939: {"name": "Bellibolt", "type": ["Electric"]},
    940: {"name": "Wattrel", "type": ["Electric", "Flying"]},
    941: {"name": "Kilowattrel", "type": ["Electric", "Flying"]},
    942: {"name": "Maschiff", "type": ["Dark"]},
    943: {"name": "Mabosstiff", "type": ["Dark"]},
    944: {"name": "Shroodle", "type": ["Poison", "Normal"]},
    945: {"name": "Grafaiai", "type": ["Poison", "Normal"]},
    946: {"name": "Bramblin", "type": ["Grass", "Ghost"]},
    947: {"name": "Brambleghast", "type": ["Grass", "Ghost"]},
    948: {"name": "Toedscool", "type": ["Ground", "Grass"]},
    949: {"name": "Toedscruel", "type": ["Ground", "Grass"]},
    950: {"name": "Klawf", "type": ["Rock"]},
    951: {"name": "Capsakid", "type": ["Grass"]},
    952: {"name": "Scovillain", "type": ["Grass", "Fire"]},
    953: {"name": "Rellor", "type": ["Bug"]},
    954: {"name": "Rabsca", "type": ["Bug", "Psychic"]},
    955: {"name": "Flittle", "type": ["Psychic"]},
    956: {"name": "Espathra", "type": ["Psychic"]},
    957: {"name": "Tinkatink", "type": ["Fairy", "Steel"]},
    958: {"name": "Tinkatuff", "type": ["Fairy", "Steel"]},
    959: {"name": "Tinkaton", "type": ["Fairy", "Steel"]},
    960: {"name": "Wiglett", "type": ["Water"]},
    961: {"name": "Wugtrio", "type": ["Water"]},
    962: {"name": "Bombirdier", "type": ["Flying", "Dark"]},
    963: {"name": "Finizen", "type": ["Water"]},
    964: {"name": "Palafin", "type": ["Water"]},
    965: {"name": "Varoom", "type": ["Steel", "Poison"]},
    966: {"name": "Revavroom", "type": ["Steel", "Poison"]},
    967: {"name": "Cyclizar", "type": ["Dragon", "Normal"]},
    968: {"name": "Orthworm", "type": ["Steel"]},
    969: {"name": "Glimmet", "type": ["Rock", "Steel"]},
    970: {"name": "Glimmora", "type": ["Rock", "Poison"]},
    971: {"name": "Greavard", "type": ["Ghost"]},
    972: {"name": "Houndstone", "type": ["Ghost"]},
    973: {"name": "Flamigo", "type": ["Flying", "Fighting"]},
    974: {"name": "Cetoddle", "type": ["Ice"]},
    975: {"name": "Cetitan", "type": ["Ice"]},
    976: {"name": "Veluza", "type": ["Water", "Psychic"]},
    977: {"name": "Dondozo", "type": ["Water"]},
    978: {"name": "Tatsugiri", "type": ["Dragon", "Water"]},
    979: {"name": "Annihilape", "type": ["Fighting", "Ghost"]},
    980: {"name": "Clodsire", "type": ["Poison", "Ground"]},
    981: {"name": "Farigiraf", "type": ["Normal", "Psychic"]},
    982: {"name": "Dudunsparce", "type": ["Normal"]},
    983: {"name": "Kingambit", "type": ["Dark", "Steel"]},
    984: {"name": "Great Tusk", "type": ["Ground", "Fighting"]},
    985: {"name": "Scream Tail", "type": ["Fairy", "Psychic"]},
    986: {"name": "Brute Bonnet", "type": ["Grass", "Dark"]},
    987: {"name": "Flutter Mane", "type": ["Ghost", "Fairy"]},
    988: {"name": "Slither Wing", "type": ["Bug", "Fighting"]},
    989: {"name": "Sandy Shocks", "type": ["Electric", "Ground"]},
    990: {"name": "Iron Treads", "type": ["Ground", "Steel"]},
    991: {"name": "Iron Bundle", "type": ["Ice", "Water"]},
    992: {"name": "Iron Hands", "type": ["Fighting", "Electric"]},
    993: {"name": "Iron Jugulis", "type": ["Dark", "Flying"]},
    994: {"name": "Iron Moth", "type": ["Fire", "Poison"]},
    995: {"name": "Iron Thorns", "type": ["Rock", "Electric"]},
    996: {"name": "Frigibax", "type": ["Dragon", "Ice"]},
    997: {"name": "Arctibax", "type": ["Dragon", "Ice"]},
    998: {"name": "Baxcalibur", "type": ["Dragon", "Ice"]},
    999: {"name": "Gimmighoul", "type": ["Steel", "Ghost"]},
    1000: {"name": "Gholdengo", "type": ["Steel", "Ghost"]},
    1001: {"name": "Wo-Chien", "type": ["Dark", "Grass"]},
    1002: {"name": "Chien-Pao", "type": ["Dark", "Ice"]},
    1003: {"name": "Ting-Lu", "type": ["Dark", "Ground"]},
    1004: {"name": "Chi-Yu", "type": ["Dark", "Fire"]},
    1005: {"name": "Roaring Moon", "type": ["Dragon", "Dark"]},
    1006: {"name": "Iron Valiant", "type": ["Fairy", "Fighting"]},
    1007: {"name": "Koraidon", "type": ["Fighting", "Dragon"]},
    1008: {"name": "Miraidon", "type": ["Dragon", "Electric"]},
    1009: {"name": "Walking Wake", "type": ["Water", "Dragon"]},
    1010: {"name": "Iron Leaves", "type": ["Grass", "Psychic"]},
    1011: {"name": "Dipplin", "type": ["Grass", "Dragon"]},
    1012: {"name": "Poltchageist", "type": ["Grass", "Ghost"]},
    1013: {"name": "Sinistcha", "type": ["Grass", "Ghost"]},
    1014: {"name": "Okidogi", "type": ["Poison", "Fighting"]},
    1015: {"name": "Munkidori", "type": ["Poison", "Psychic"]},
    1016: {"name": "Fezandipiti", "type": ["Poison", "Fairy"]},
    1017: {"name": "Ogerpon", "type": ["Grass"]},
    1018: {"name": "Archaludon", "type": ["Steel", "Dragon"]},
    1019: {"name": "Hydrapple", "type": ["Grass", "Dragon"]},
    1020: {"name": "Gouging Fire", "type": ["Fire", "Dragon"]},
    1021: {"name": "Raging Bolt", "type": ["Electric", "Dragon"]},
    1022: {"name": "Iron Boulder", "type": ["Rock", "Psychic"]},
    1023: {"name": "Iron Crown", "type": ["Steel", "Psychic"]},
    1024: {"name": "Terapagos", "type": ["Normal"]},
    1025: {"name": "Pecharunt", "type": ["Poison", "Ghost"]},
}